### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Códigos de erro para funções personalizadas. Os códigos de erro aparecerão na célula que chamou a função.


  Mensagens de erro personalizadas aparecem além desses códigos de erro. As mensagens personalizadas são exibidas no menu indicador de erro, que é acessado ao passar o sinalizador de erro em cada célula com um erro.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que a função usada está sendo dividida por zero ou por células vazias. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que há um erro de digitação no nome da função. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que há um problema com um número na função. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que a função se refere a uma célula inválida. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que um valor na função é do tipo de dados incorreto. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que a função ou serviço não está disponível. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Esse código de erro indica que os intervalos na função não fazem interseção. Não é possível usar uma mensagem de erro personalizada. \[[Conjunto de APIs: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
metadata:
  ms.openlocfilehash: 7136ddf8accdca9a80f9529f0594b36f38f4c63d
  ms.sourcegitcommit: 3bab97ab3b91da7cca497f6fc895408a76bd8b46
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 11/18/2020
  ms.locfileid: "49195543"
