### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Códigos de erro para funções personalizadas. Os códigos de erro aparecerão na célula que invocou a função.


  Mensagens de erro personalizadas aparecem além desses códigos de erro. Mensagens personalizadas são exibidas no menu de indicador de erro, que é acessado ao passar o mouse sobre o sinalizador de erro em cada célula com um erro.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que a função usada está dividindo por zero ou células vazias. Uma mensagem de erro personalizada não pode ser usada. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que há um erro de digitação no nome da função. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Uma mensagem de erro personalizada não pode ser usada. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que há um problema com um número na função. Uma mensagem de erro personalizada não pode ser usada. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que a função se refere a uma célula inválida. Observe que esse código de erro é suportado como um erro de entrada de função personalizada, mas não como um erro de saída de função personalizada. Uma mensagem de erro personalizada não pode ser usada. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que um valor na função é do tipo de dados errado. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que a função ou serviço não está disponível. Uma mensagem de erro personalizada pode ser usada além do código de erro, se desejado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Este código de erro indica que os intervalos na função não se cruzam. Uma mensagem de erro personalizada não pode ser usada. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: 2c8673b5e49abbb312138d3436da25613d17df74
  ms.sourcegitcommit: a8a86cfcaff5ad7dacc653d63502c76b1fedbebe
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 03/26/2021
  ms.locfileid: "51267968"
